version: '3'

services:
  authe: 
    container_name: chat
    image: chat_image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - chat_v:/user/app
    ports:
      - 9059:8000
    networks:
      - pingpong.net

  # postgresql:
  #   container_name: postgresql
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - PgreSgl_v:/var/lib/postgresql/data
  #   networks:
  #     - net
  #   env_file: .env

volumes:
  chat_v:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: 'chat'
  # PgreSgl_v:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '../PgreSql'

networks:
  pingpong.net:
    external: true