# Generated by Django 5.0.6 on 2024-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_message_msg_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
