# Generated by Django 5.0.6 on 2024-08-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='last_updaet',
            new_name='last_update',
        ),
    ]
