# Generated by Django 5.0.6 on 2024-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_last_updaet_chat_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='chat',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_text',
            field=models.CharField(max_length=50),
        ),
    ]
