# Generated by Django 3.1 on 2024-05-09 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.CharField(max_length=255, unique=True, verbose_name='socket')),
                ('joined_at', models.DateTimeField(default=datetime.datetime(2024, 5, 9, 13, 37, 51, 579446), verbose_name='create date')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
            ],
        ),
    ]
