# Generated by Django 3.1 on 2024-06-09 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='groupe',
            field=models.CharField(max_length=50, null=True, verbose_name='groupe'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='login',
            field=models.CharField(max_length=50, null=True, verbose_name='login'),
        ),
    ]
