# Generated by Django 3.1 on 2024-07-15 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50, unique=True, verbose_name='player1')),
                ('player2', models.CharField(max_length=50, unique=True, verbose_name='player2')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date')),
                ('round', models.IntegerField(default=1, verbose_name='round')),
                ('game_started', models.BooleanField(default=False, verbose_name='game_started')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='login')),
                ('is_connected', models.BooleanField(default=False, verbose_name='is_connected')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('channel_id', models.CharField(max_length=255, null=True, verbose_name='socket')),
                ('side', models.IntegerField(default=0, verbose_name='side')),
                ('imageURL', models.CharField(default='None', max_length=500, verbose_name='imageURL')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='login')),
                ('games_played', models.IntegerField(default=0, verbose_name='games_played')),
                ('wins', models.IntegerField(default=0, verbose_name='wins')),
                ('loss', models.IntegerField(default=0, verbose_name='loss')),
                ('goals_scored', models.IntegerField(default=0, verbose_name='goals_scored')),
                ('goals_conceded', models.IntegerField(default=0, verbose_name='goals_conceded')),
            ],
        ),
        migrations.CreateModel(
            name='PonGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(default='', max_length=50, verbose_name='gamename')),
                ('player1', models.CharField(max_length=50, verbose_name='player1')),
                ('player2', models.CharField(max_length=50, verbose_name='player2')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date')),
                ('goals_order', models.CharField(default='', max_length=10, verbose_name='goals_order')),
                ('p1goal', models.IntegerField(default=0, verbose_name='p1goal')),
                ('p2goal', models.IntegerField(default=0, verbose_name='p2goal')),
                ('winner', models.CharField(default='', max_length=50, verbose_name='winner')),
            ],
        ),
    ]
